import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import eventService from '../services/eventService';
import { motion } from 'framer-motion';
import { 
  BarChart3, Users, Download, Eye, Trash2, 
  TrendingUp, Calendar, MapPin, Search, Plus, Sparkles 
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar } from 'recharts';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

const AdminDashboard = () => {
  const { user } = useAuth();
  const [events, setEvents] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const navigate = useNavigate();

  useEffect(() => {
    setEvents(eventService.getEvents());
  }, []);

  const stats = [
    { name: 'Active Events', value: events.filter(e => e.status === 'Upcoming').length, icon: Calendar, color: 'text-blue-600', bg: 'bg-blue-50' },
    { name: 'Total Pupils', value: events.reduce((acc, curr) => acc + (curr.participants?.length || 0), 0), icon: Users, color: 'text-pink-600', bg: 'bg-pink-50' },
    { name: 'Avg. Attendance', value: '84%', icon: TrendingUp, color: 'text-green-600', bg: 'bg-green-50' },
    { name: 'New Registrations', value: '+12%', icon: Sparkles, color: 'text-amber-600', bg: 'bg-amber-50' },
  ];

  // Mock chart data
  const chartData = [
    { name: 'Mon', registrations: 400, events: 240 },
    { name: 'Tue', registrations: 300, events: 139 },
    { name: 'Wed', registrations: 200, events: 980 },
    { name: 'Thu', registrations: 278, events: 390 },
    { name: 'Fri', registrations: 189, events: 480 },
    { name: 'Sat', registrations: 239, events: 380 },
    { name: 'Sun', registrations: 349, events: 430 },
  ];

  const generateReport = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text('Performance Report', 14, 22);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Generated by: Admin | Date: ${new Date().toLocaleDateString()}`, 14, 30);

    const tableData = events.map(e => [e.title, e.date, e.venue, e.participants.length, e.status]);
    doc.autoTable({
      startY: 40,
      head: [['Event Title', 'Date', 'Venue', 'Participants', 'Status']],
      body: tableData,
      headStyles: { fillColor: [37, 99, 235], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [241, 245, 249] },
    });
    doc.save('Campus_Analytics.pdf');
  };

  const filteredEvents = events.filter(e => 
    e.title.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="p-6 md:p-12 bg-slate-50 min-h-screen">
      <div className="max-w-7xl mx-auto space-y-10">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div>
            <h1 className="text-4xl font-black text-slate-900 mb-2">Performance Center</h1>
            <p className="text-slate-500 font-medium">Monitoring {events.length} active opportunities across campus</p>
          </div>
          <div className="flex gap-4 w-full md:w-auto">
            <button onClick={generateReport} className="btn-outline-unstop flex-1 md:flex-none flex items-center justify-center gap-2">
              <Download size={18} />
              Export PDF
            </button>
            <button onClick={() => navigate('/create-event')} className="btn-unstop flex-1 md:flex-none flex items-center justify-center gap-2">
              <Plus size={20} />
              New Event
            </button>
          </div>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {stats.map((stat, idx) => (
            <motion.div 
              key={idx}
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: idx * 0.1 }}
              className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex items-center gap-5"
            >
              <div className={`${stat.bg} ${stat.color} p-4 rounded-2xl`}>
                <stat.icon size={24} />
              </div>
              <div>
                <p className="text-slate-400 text-sm font-bold uppercase tracking-wider">{stat.name}</p>
                <p className="text-2xl font-black text-slate-900">{stat.value}</p>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Charts & Table Section */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Chart Area */}
            <div className="lg:col-span-2 bg-white p-8 rounded-3xl border border-slate-100 shadow-sm">
                <h3 className="text-lg font-black text-slate-900 mb-8 border-l-4 border-blue-600 pl-4 uppercase">Registration Trends</h3>
                <div className="h-[350px] w-full">
                    <ResponsiveContainer width="100%" height="100%">
                        <AreaChart data={chartData}>
                            <defs>
                                <linearGradient id="colorReg" x1="0" y1="0" x2="0" y2="1">
                                    <stop offset="5%" stopColor="#2563eb" stopOpacity={0.1}/>
                                    <stop offset="95%" stopColor="#2563eb" stopOpacity={0}/>
                                </linearGradient>
                            </defs>
                            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#94a3b8', fontSize: 12, fontWeight: 600}} dy={10} />
                            <YAxis axisLine={false} tickLine={false} tick={{fill: '#94a3b8', fontSize: 12, fontWeight: 600}} />
                            <Tooltip 
                                contentStyle={{borderRadius: '16px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)', fontWeight: 700}}
                            />
                            <Area type="monotone" dataKey="registrations" stroke="#2563eb" strokeWidth={4} fillOpacity={1} fill="url(#colorReg)" />
                        </AreaChart>
                    </ResponsiveContainer>
                </div>
            </div>

            {/* Quick Actions / Recent Activity */}
            <div className="bg-white p-8 rounded-3xl border border-slate-100 shadow-sm flex flex-col">
                <h3 className="text-lg font-black text-slate-900 mb-8 border-l-4 border-pink-500 pl-4 uppercase">Activity Feed</h3>
                <div className="space-y-6 flex-1 overflow-y-auto max-h-[350px] pr-2">
                    {events.flatMap(e => e.participants.slice(0,2)).map((p, i) => (
                        <div key={i} className="flex items-center gap-4 group">
                            <div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center font-bold text-slate-500 text-xs uppercase group-hover:bg-blue-600 group-hover:text-white transition-all">
                                {p.charAt(0)}
                            </div>
                            <div>
                                <p className="text-sm font-black text-slate-900 italic">{p}</p>
                                <p className="text-[10px] text-slate-400 font-bold uppercase">Registered for Tech Innovation</p>
                            </div>
                            <span className="ml-auto text-[10px] font-bold text-slate-300">2m ago</span>
                        </div>
                    ))}
                </div>
                <button className="mt-8 text-blue-600 font-black text-sm uppercase tracking-widest hover:translate-x-1 transition-transform inline-flex items-center gap-2">
                    View All Activity <Sparkles size={14} />
                </button>
            </div>
        </div>

        {/* Detailed Table */}
        <div className="bg-white rounded-3xl border border-slate-100 shadow-sm overflow-hidden">
            <div className="p-8 border-b border-slate-100 flex flex-col md:flex-row justify-between items-center gap-4">
                <h3 className="text-lg font-black text-slate-900 uppercase tracking-tight">Management Registry</h3>
                <div className="relative w-full md:w-80">
                    <Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                    <input 
                        type="text" 
                        placeholder="Filter by title..." 
                        className="input-unstop pl-12 py-2.5 text-sm" 
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                    />
                </div>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full text-left">
                    <thead>
                        <tr className="bg-slate-50/50 text-slate-500 text-[10px] font-black uppercase tracking-widest border-b border-slate-100">
                            <th className="px-8 py-5">Event Detail</th>
                            <th className="px-8 py-5">Engagement</th>
                            <th className="px-8 py-5">Status</th>
                            <th className="px-8 py-5 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-50">
                        {filteredEvents.map((event) => (
                            <tr key={event.id} className="hover:bg-slate-50/50 transition-colors">
                                <td className="px-8 py-6">
                                    <div className="flex items-center gap-4">
                                        <div className="w-12 h-12 bg-blue-50 rounded-xl flex items-center justify-center text-blue-600">
                                            <Calendar size={20} />
                                        </div>
                                        <div>
                                            <p className="font-black text-slate-900">{event.title}</p>
                                            <div className="flex gap-3 mt-1 text-[10px] font-bold text-slate-400">
                                                <span className="flex items-center gap-1"><MapPin size={10} /> {event.venue}</span>
                                                <span className="flex items-center gap-1"><Calendar size={10} /> {event.date}</span>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td className="px-8 py-6">
                                    <div className="flex flex-col gap-1.5">
                                        <div className="flex justify-between items-center w-32">
                                            <span className="text-[10px] font-black text-slate-500 uppercase">{event.participants.length} Active</span>
                                            <span className="text-[10px] font-black text-blue-600">72%</span>
                                        </div>
                                        <div className="w-32 h-1.5 bg-slate-100 rounded-full overflow-hidden">
                                            <div className="h-full bg-blue-600 rounded-full" style={{width: `${Math.min(event.participants.length * 10, 100)}%`}}></div>
                                        </div>
                                    </div>
                                </td>
                                <td className="px-8 py-6">
                                    <span className={`px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest ${
                                        event.status === 'Upcoming' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                                    }`}>
                                        {event.status}
                                    </span>
                                </td>
                                <td className="px-8 py-6 text-right">
                                    <div className="flex justify-end gap-2">
                                        <button className="p-2.5 hover:bg-blue-50 text-slate-400 hover:text-blue-600 rounded-xl transition-all"><Eye size={18}/></button>
                                        <button className="p-2.5 hover:bg-red-50 text-slate-400 hover:text-red-500 rounded-xl transition-all"><Trash2 size={18}/></button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
      </div>
    </div>
  );
};

export default AdminDashboard;
